In [8]:
from PIL import Image
import numpy as np


In [41]:
from PIL import Image
#Read the two images
image1 = Image.open("Pictures/set_1.png")
image1.show()
image2 = Image.open("Pictures/set_2.png")
image2.show()
#resize, first image
image1 = image1.resize((30, 30))
image1_size = image1.size
image2_size = image2.size
new_image = Image.new('RGB',(2*image1_size[0], image1_size[1]), (250,250,250))
new_image.paste(image1,(0,0))
new_image.paste(image2,(image1_size[0],0))
new_image.save("Pictures/merged_image.jpg","JPEG")
new_image.show()

In [42]:
an_image = Image.open("Pictures/set_1.png")


image_sequence = an_image.getdata()
image_array = np.array(image_sequence)

print(image_array)
x,y = an_image.size
lis1 =[]
n=0
for i in range(y):
    sub_list = []
    for j in range(x):
        num = n
        sub_list.append(image_array[num])
        n+=1
    lis1.append(sub_list)

[255 255 255 255 255 255 255 255 255 255   0   0   0   0 255 255 255 255
 255 255 255 255 255 255 255 255 255   0   0   0   0   0   0   0 255 255
 255 255 255 255 255 255 255 255 255   0   0   0   0   0   0   0   0   0
 255 255 255 255 255 255 255 255 255   0   0   0   0   0 255 255   0   0
   0 255 255 255 255 255 255 255   0   0   0   0   0 255 255 255 255   0
   0   0 255 255 255 255 255 255   0   0   0   0   0 255 255 255 255 255
 255   0   0 255 255 255 255 255   0   0   0   0   0   0 255 255 255 255
 255 255   0   0 255 255 255 255   0   0   0   0   0   0 255 255 255 255
 255 255 255   0   0   0 255 255 255   0   0   0   0   0   0   0 255 255
 255 255 255 255   0   0   0 255 255   0   0   0   0   0   0   0   0 255
 255 255 255 255 255   0   0   0 255 255   0   0   0 255 255   0   0   0
 255 255 255 255 255 255   0   0   0 255 255   0   0 255 255 255   0   0
   0 255 255 255 255 255 255 255   0   0 255 255 255 255 255 255 255   0
   0   0 255 255 255 255 255 255 255   0   0 255 25

In [43]:
print(np.array(lis1))

[[255 255 255 255 255 255 255 255 255 255   0   0   0   0 255 255 255 255
  255]
 [255 255 255 255 255 255 255 255   0   0   0   0   0   0   0 255 255 255
  255]
 [255 255 255 255 255 255 255   0   0   0   0   0   0   0   0   0 255 255
  255]
 [255 255 255 255 255 255   0   0   0   0   0 255 255   0   0   0 255 255
  255]
 [255 255 255 255   0   0   0   0   0 255 255 255 255   0   0   0 255 255
  255]
 [255 255 255   0   0   0   0   0 255 255 255 255 255 255   0   0 255 255
  255]
 [255 255   0   0   0   0   0   0 255 255 255 255 255 255   0   0 255 255
  255]
 [255   0   0   0   0   0   0 255 255 255 255 255 255 255   0   0   0 255
  255]
 [255   0   0   0   0   0   0   0 255 255 255 255 255 255   0   0   0 255
  255]
 [  0   0   0   0   0   0   0   0 255 255 255 255 255 255   0   0   0 255
  255]
 [  0   0   0 255 255   0   0   0 255 255 255 255 255 255   0   0   0 255
  255]
 [  0   0 255 255 255   0   0   0 255 255 255 255 255 255 255   0   0 255
  255]
 [255 255 255 255 255   0   

In [32]:
x,y = an_image.size

In [33]:
x,y = an_image.size
lis =[]
n=0
for i in range(y):
    sub_list = []
    for j in range(x):
        num = n
        sub_list.append(image_array[num])
        n+=1
    lis.append(sub_list)

In [39]:
print(np.array(lis))

[[255 255 255 255   0   0   0   0   0   0   0   0 255 255 255 255 255]
 [255 255   0   0   0   0   0   0   0   0   0   0   0   0 255 255 255]
 [255   0   0   0   0   0   0   0   0   0   0   0   0   0 255 255 255]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 255 255]
 [  0   0   0   0   0   0 255 255 255 255   0   0   0   0   0   0 255]
 [255   0   0   0   0 255 255 255 255 255 255   0   0   0   0   0 255]
 [255 255 255   0   0 255 255 255 255 255 255 255   0   0   0   0 255]
 [255 255 255 255 255 255 255 255 255 255 255 255   0   0   0   0 255]
 [255 255 255 255 255 255 255 255 255 255 255 255   0   0   0   0   0]
 [255 255 255 255 255 255 255 255 255 255 255 255   0   0   0   0   0]
 [255 255 255 255 255 255 255 255 255 255 255 255   0   0   0   0   0]
 [255 255 255 255 255 255 255 255 255 255 255 255   0   0   0   0   0]
 [255 255 255 255 255 255 255 255 255 255 255 255   0   0   0   0   0]
 [255 255 255 255 255 255 255 255 255 255 255 255   0   0   0   0   0]
 [255 